// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaXROLVF_ZRq4WFe56Ne8mXIFiJD2F3VE',
    appId: '1:464880503125:web:8ea585ed6e75caccc747dc',
    messagingSenderId: '464880503125',
    projectId: 'spectoxr-ar-menu',
    authDomain: 'spectoxr-ar-menu.firebaseapp.com',
    storageBucket: 'spectoxr-ar-menu.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAx75JfPZrT8lZq4lYW-txyZ0iq_tS0Vv4',
    appId: '1:464880503125:android:b079b868c61ab47bc747dc',
    messagingSenderId: '464880503125',
    projectId: 'spectoxr-ar-menu',
    storageBucket: 'spectoxr-ar-menu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD96ZYpLqeBSAaztmWItONU7Sv0YuaidJE',
    appId: '1:464880503125:ios:e53e336ea00f9f9fc747dc',
    messagingSenderId: '464880503125',
    projectId: 'spectoxr-ar-menu',
    storageBucket: 'spectoxr-ar-menu.firebasestorage.app',
    iosBundleId: 'com.reachspectoxr.arMenu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD96ZYpLqeBSAaztmWItONU7Sv0YuaidJE',
    appId: '1:464880503125:ios:e53e336ea00f9f9fc747dc',
    messagingSenderId: '464880503125',
    projectId: 'spectoxr-ar-menu',
    storageBucket: 'spectoxr-ar-menu.firebasestorage.app',
    iosBundleId: 'com.reachspectoxr.arMenu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaXROLVF_ZRq4WFe56Ne8mXIFiJD2F3VE',
    appId: '1:464880503125:web:59c619d28d11d4cac747dc',
    messagingSenderId: '464880503125',
    projectId: 'spectoxr-ar-menu',
    authDomain: 'spectoxr-ar-menu.firebaseapp.com',
    storageBucket: 'spectoxr-ar-menu.firebasestorage.app',
  );
}
